---
# Run using the following:
# ansible-playbook --ask-sudo-pass common-apps.yml
- hosts: 127.0.0.1
  connection: local
  become_user: root
  vars:
  tasks:
    - name: Install snapd
      apt: pkg=snapd state=present
      become: yes

    - name: postgres
      become: yes
      apt:
        pkg=postgresql-client-10
        state=present

    - name: postgres
      become: yes
      apt:
        pkg=postgresql-client-common
        state=present

    - name: postgres
      become: yes
      apt:
        pkg=postgresql-common
        state=present

    - name: swig
      become: yes
      apt:
        pkg=swig
        state=present

    - name: openssl
      become: yes
      apt:
        pkg=openssl
        state=present

    - name: net-tools
      become: yes
      apt:
        pkg=net-tools
        state=present

    - name: make
      become: yes
      apt:
        pkg=make
        state=present

    - name: python3-pip
      become: yes
      apt:
        pkg=python3-pip
        state=present

    - name: linuxbrew-wrapper
      become: yes
      apt:
        pkg=linuxbrew-wrapper
        state=present
