---
# Run using the following:
# ansible-playbook --ask-sudo-pass docker.yml
- hosts: 127.0.0.1
  connection: local
  sudo: True
  vars:
    - apt_file: /etc/apt/sources.list.d/docker.list
    - compose_file: /usr/local/bin/docker-compose
    - current_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Add apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Update apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: yes
      become: yes

    - name: Install apt-transport-https
      apt: pkg=apt-transport-https state=present
      become: yes

    - name: Install ca-certificates
      apt: pkg=ca-certificates state=present
      become: yes

    - name: Install Curl
      apt: pkg=curl state=present
      become: yes

    - name: Install software-properties-common
      apt: pkg=software-properties-common state=present
      become: yes

    - name: Install docker-ce
      apt: pkg=docker-ce state=present
      become: yes

    - name: adding existing user "{{current_user}}" to group docker
      user:
        name: "{{current_user}}"
        groups: docker
        append: yes

    - file:
        path: /usr/local/bin
        state: directory
        mode: 755
        owner: root
        group: root	

    - name: Does the docker-compose file exist?
      command: test -f {{compose_file}}
      register: docker_compose_exists
      ignore_errors: True

    - name: Get docker compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o "{{ compose_file }}"
      when: docker_compose_exists.rc == 1

    - name: Get docker compose
      shell: chmod +x "{{ compose_file }}"
      when: docker_compose_exists.rc == 1

    - debug:
        msg: "NOTE: You must logout and login again in order for your user to be added to the docker group which ensures docker-compose works correctly."
